### ISSUE TITLE
How to train our own dataset

### ISSUE THREAD

**Issue by numancelik34** [evanmy/sae#1]
Thanks for this interesting repo. 
this is not an issue but for an advice. Can we apply this model to other biomedical dataset for tissue and cell segmentation? 

Thanks

**Comment by evanmy** [comment]
Thank you for your question. For the current model, we assume that we have 1 labeled example, which is used as the prior for the variational autoencoder. The labeled example can be either a probabilistic atlas or just from a random subject. If it is the latter, you need to add some blur to the label. This is because in order to get good accuracy the network needs to be able to capture heterogeneity in the brain population. By blurring the label, we are adding uncertainty around the border which allows the network to have predictions that can vary from the prior. This also implies that the prior and your input images have some spatial alignment. For this paper, the prior and the unlabeled MRI were affine pre-registered before running the model.

We are currently exploring the use of flexible priors that have a built-in deformation model. By adding a spatial transformer (deformation model) to the prior, we can hopefully remove the need of pre-registering the images before training and handle complications like moving organs.

As for cells, I imagine that each image have different amount of cells located arbitrary within the image. Therefore, a fixed prior would not be able to provide enough information to segment your images.
